version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - hsahovic
  assignees:
  - hsahovic
  labels:
  - dependencies
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
  - dependency-name: pyre-check
    versions:
    - 0.0.59
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
    - hsahovic
  assignees:
    - hsahovic
  labels:
    - CI actions
