name: Nightly tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  nightly:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
  nightly-extra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run nightly-only checks
        run: pytest -x strict_integration_tests/
